/**
 * The persisted world document.
 *
 * This is deliberately *not* the runtime state. It carries only what a person
 * authored - layout, floor, furniture placement, glazing - and nothing that can
 * be recomputed or that belongs to a session:
 *
 *   - **walls are derived** from the floor tiles, so they are recomputed on load
 *     rather than stored. Storing them would let a saved room disagree with its
 *     own layout.
 *   - **furniture definitions are not stored**, only the type id. The definition
 *     is generated by the Sprite Factory; embedding a copy would bloat every
 *     save and go stale the moment the catalogue is regenerated.
 *   - **players, tools, hover and camera** are session state and never persist.
 *
 * The shape is designed to survive the move to a server: it is plain JSON,
 * every room is addressable by id, and each carries `revision` and `updatedAt`
 * so a backend can reject a stale write rather than silently clobbering it.
 */

/** Bump when the document shape changes in a way older data cannot satisfy. */
export const SCHEMA_VERSION = 1

export interface PersistedFurniture {
  id: string
  /** Catalogue id. The definition is looked up on load, never stored. */
  type: string
  x: number
  y: number
  /**
   * Screen pixels above whatever it rests on. Absent means on the floor.
   *
   * Stored rather than recomputed: resolving a stack on load would mean
   * ordering pieces bottom-up and re-deriving heights that the placement
   * already worked out.
   */
  z?: number
  direction?: string
}

export interface PersistedRoom {
  id: string
  name: string
  width: number
  height: number
  floorTexture?: string
  floorTiles: Array<{ x: number; y: number; texture?: string }>
  windows: Array<{ x: number; y: number; edge: 'north' | 'west' }>
  furniture: PersistedFurniture[]
  doorway?: { x: number; y: number; type: 'north-east' | 'north-west' }
  spawnPoint?: { x: number; y: number }
  /** Incremented on every save. A server can use it for optimistic locking. */
  revision: number
  updatedAt: string
}

export interface WorldDocument {
  schemaVersion: number
  rooms: PersistedRoom[]
  currentRoomId: string | null
  updatedAt: string
}

/**
 * Storage backend.
 *
 * Async on purpose. `localStorage` is synchronous, but writing the interface
 * around it would mean rewriting every call site the day this moves to a
 * server, so the local implementation returns resolved promises instead.
 */
export interface WorldStore {
  /** The stored world, or null if nothing has been saved yet. */
  load(): Promise<WorldDocument | null>
  /**
   * Persist the world.
   *
   * Returns what was actually stored: a server may bump revisions or reject a
   * stale write, so callers should trust the response over what they sent.
   */
  save(document: WorldDocument): Promise<WorldDocument>
  /** Forget everything. Used by the reset control while there is no server. */
  clear(): Promise<void>
}
