import React, { createContext, useContext, useReducer, ReactNode, useEffect, useRef } from 'react'
import { getWorldStore } from '../persistence/worldStore'
import { fromPersistedRoom, toWorldDocument } from '../persistence/serialise'
import type { WorldDocument } from '../persistence/types'
import { getProfileStore, toProfileDocument } from '../persistence/profileStore'
import roomLayoutDefinitions from '../assets/roomLayouts.json'
import type { WallEdge } from '../data/structureSprites'
import { Appearance, appearanceForSeed, DEFAULT_APPEARANCE } from '../data/appearance'
import { getHairStyles, getOutfits } from '../data/characterSprites'

// Types
export interface Player {
  id: number
  x: number
  y: number
  targetX: number
  targetY: number
  color: string
  name: string
  size: number
  isMoving: boolean
  moveSpeed: number
  moveTimer: number
  moveDelay: number
  path: Array<{ x: number; y: number }>
  pathIndex: number
  action: PlayerAction
  actionTimer: number
  /**
   * How long the action lasts, from the furniture's own data.
   *
   * 0 means "until they walk away", which is what sitting and lying are. The
   * loop used to expire every action after a hardcoded three seconds, which is
   * neither what the catalogue says nor what a chair should do.
   */
  actionDuration: number
  /**
   * What the player meant to do when they set off, if they clicked an object.
   *
   * Arriving somewhere is not the same as intending to use what is there:
   * without this, walking past a desk on the way to a chair would stop and use
   * the desk. Cleared on arrival.
   */
  intent: PlayerIntent | null
  lastDirection: string
  /** Hair, outfit and colours. Every player has one; only ours is editable. */
  appearance: Appearance
}

/**
 * One per interaction type the Sprite Factory can emit, plus the two the
 * context menu offers. A type the game cannot draw is a spot nothing can reach.
 */
export type PlayerAction = 'idle' | 'sitting' | 'laying' | 'using' | 'dancing' | 'waving'

export interface PlayerIntent {
  /** Interaction type to perform on arrival. */
  type: string
  /** The piece it belongs to, so a moved or deleted one is simply forgotten. */
  furnitureId: string
}

export interface Furniture {
  id: string
  x: number
  y: number
  type: string
  /** Rendered orientation. Defaults to the definition's default direction. */
  direction?: FurnitureDirection
  definition: FurnitureDefinition
}

export type FurnitureDirection = 'north' | 'south' | 'east' | 'west'

/** Where a piece can be placed. Generated by the Sprite Factory. */
export type FurniturePlacement = 'floor' | 'wall' | 'ceiling'

/**
 * One rendered orientation of a piece of furniture.
 *
 * `anchorX`/`anchorY` locate the centre of the piece's origin tile within the
 * sprite, which is what lets a 78px-tall bookshelf and a flat rug both be drawn
 * from the same tile coordinate without per-item fudge factors.
 */
/** A contact shadow, anchored to the same tile as the sprite it belongs to. */
export interface SpriteShadow {
  url: string
  file: string
  width: number
  height: number
  anchorX: number
  anchorY: number
}

export interface FurnitureSprite {
  url: string
  file: string
  index: number
  width: number
  height: number
  anchorX: number
  anchorY: number
  footprint: { width: number; height: number }
  interactions: FurnitureInteraction[]
  shadow?: SpriteShadow
}

export interface FurnitureDefinition {
  id: string
  name: string
  sprite: string
  width: number
  height: number
  interactions: FurnitureInteraction[]
  collision: FurnitureCollision
  walkable: boolean
  stackable: boolean
  rotatable: boolean
  category: 'seating' | 'decoration' | 'functional' | 'flooring' | 'wall'
  placement?: FurniturePlacement
  /** Orientation whose footprint matches `width`/`height`. */
  defaultDirection?: FurnitureDirection
  /** Every rendered orientation, keyed by direction. */
  sprites?: Record<string, FurnitureSprite>
  /** Every colour in the sprite, for palette-aware UI. */
  palette?: string[]
}

export interface FurnitureInteraction {
  type: 'sit' | 'lay' | 'stand' | 'use' | 'dance' | 'sleep'
  positions: FurniturePosition[]
  animation?: string
  duration?: number
}

export interface FurniturePosition {
  x: number
  y: number
  direction: 'north' | 'south' | 'east' | 'west' | 'north-east' | 'north-west' | 'south-east' | 'south-west'
  /**
   * Pixel offset from the tile's screen position to where the player's sprite
   * belongs - the seat of a chair, the mattress of a bed. Generated by
   * projecting the interaction point through the same camera as the sprite.
   */
  offsetX?: number
  offsetY?: number
  /** Whether the player draws over the furniture sprite or under it. */
  layer?: 'front' | 'behind'
}

export interface FurnitureCollision {
  blocksMovement: boolean
  blocksVision: boolean
  height: number // Height in tiles (0 = floor level, 1 = 1 tile high, etc.)
  shape: 'rectangle' | 'circle' | 'custom'
  customShape?: Array<{ x: number; y: number }>
}

export interface Room {
  id: string
  name: string
  width: number
  height: number
  floorTiles: Array<{ x: number; y: number; texture?: string }>
  furniture: Furniture[]
  /**
   * Wall panels, each on the edge of a floor tile it belongs to.
   *
   * Previously walls were stored on the empty tile *outside* the floor and then
   * drawn back two tiles with a magic offset. Anchoring them to the tile they
   * enclose means the sprite's own anchor positions them, with no fudge.
   */
  walls: Array<{ x: number; y: number; edge: WallEdge }>
  /**
   * Wall segments replaced by a window.
   *
   * Kept separate from `walls` so rebuilding the walls after a layout change
   * does not discard them; a window with no wall left under it is simply not
   * drawn.
   */
  windows?: Array<{ x: number; y: number; edge: WallEdge }>
  doorway?: { x: number; y: number; type: 'north-east' | 'north-west' }
  spawnPoint?: { x: number; y: number }
  floorTexture?: string
}

export interface RoomLayoutDefinition {
  id?: string
  name: string
  layout: string[]
}

export type RoomLayoutUpdate = {
  width: number
  height: number
  doorway?: { x: number; y: number; type: 'north-east' | 'north-west' }
  spawnPoint?: { x: number; y: number }
}

export interface ChatMessage {
  text: string
  timestamp: number
}

export interface GameState {
  currentTool: 'move' | 'furniture' | 'room'
  selectedFurniture: string | null
  isPlacing: boolean
  rooms: Room[]
  currentRoom: Room | null
  players: Player[]
  currentPlayerId: number
  chatMessages: ChatMessage[]
  showChat: boolean
  contextMenuVisible: boolean
  contextMenuTarget: Player | null
  hoverGridPos: { x: number; y: number } | null
  previewFurniture: { x: number; y: number; type: string; direction?: FurnitureDirection } | null
  /** Orientation the next placed piece will use. Null means its default. */
  placementDirection: FurnitureDirection | null
  /** What the Style tool does with a click. */
  styleMode: 'floor' | 'window'
}

// Action types
export type GameAction =
  | { type: 'SET_TOOL'; payload: 'move' | 'furniture' | 'room' }
  | { type: 'SELECT_FURNITURE'; payload: string | null }
  | { type: 'SET_PLACING'; payload: boolean }
  | { type: 'ADD_ROOM'; payload: Room }
  | { type: 'SET_CURRENT_ROOM'; payload: Room }
  | { type: 'DELETE_ROOM'; payload: string }
  | { type: 'RENAME_ROOM'; payload: { roomId: string; newName: string } }
  | {
      type: 'UPDATE_ROOM_LAYOUT'
      payload: { roomId: string } & RoomLayoutUpdate
    }
  | { type: 'TOGGLE_FLOOR_TILE'; payload: { x: number; y: number } }
  | { type: 'TOGGLE_WINDOW'; payload: { x: number; y: number } }
  | { type: 'SET_STYLE_MODE'; payload: 'floor' | 'window' }
  | { type: 'FILL_ROOM_FLOOR' }
  | { type: 'CLEAR_ROOM_FLOOR' }
  | { type: 'SET_FLOOR_TEXTURE'; payload: { roomId: string; texture: string } }
  | { type: 'SET_TILE_TEXTURE'; payload: { roomId: string; x: number; y: number; texture: string } }
  | { type: 'ADD_FURNITURE'; payload: Furniture }
  | { type: 'SET_PLACEMENT_DIRECTION'; payload: FurnitureDirection }
  | { type: 'ADD_PLAYER'; payload: Player }
  | { type: 'SET_CURRENT_PLAYER'; payload: number }
  | {
      type: 'MOVE_PLAYER'
      payload: {
        playerId: number
        x: number
        y: number
        path: Array<{ x: number; y: number }>
        intent?: PlayerIntent | null
      }
    }
  | {
      type: 'SET_PLAYER_ACTION'
      payload: { playerId: number; action: PlayerAction; durationMs?: number }
    }
  | { type: 'SET_PLAYER_APPEARANCE'; payload: { playerId: number; appearance: Appearance } }
  | { type: 'ADD_CHAT_MESSAGE'; payload: ChatMessage }
  | { type: 'SET_SHOW_CHAT'; payload: boolean }
  | { type: 'SHOW_CONTEXT_MENU'; payload: { x: number; y: number; player: Player } }
  | { type: 'HIDE_CONTEXT_MENU' }
  | { type: 'SET_HOVER_GRID'; payload: { x: number; y: number } | null }
  | { type: 'SET_PREVIEW_FURNITURE'; payload: { x: number; y: number; type: string; direction?: FurnitureDirection } | null }

// Initial state
const initialState: GameState = {
  currentTool: 'move',
  selectedFurniture: null,
  isPlacing: false,
  rooms: [],
  currentRoom: null,
  players: [],
  currentPlayerId: 0,
  chatMessages: [],
  showChat: false,
  contextMenuVisible: false,
  contextMenuTarget: null,
  hoverGridPos: null,
  previewFurniture: null,
  placementDirection: null,
  styleMode: 'floor',
}

// Reducer
function gameReducer(state: GameState, action: GameAction): GameState {
  switch (action.type) {
    case 'SET_TOOL':
      return { ...state, currentTool: action.payload }
    
    case 'SELECT_FURNITURE':
      return {
        ...state,
        selectedFurniture: action.payload,
        isPlacing: !!action.payload,
        placementDirection: null
      }
    
    case 'SET_PLACING':
      return { ...state, isPlacing: action.payload }
    
    case 'ADD_ROOM':
      // Idempotent: React StrictMode runs the bootstrap effect twice in
      // development, which otherwise loaded every predefined room a second
      // time and left two rooms sharing an id.
      if (state.rooms.some(room => room.id === action.payload.id)) {
        return state
      }
      return { ...state, rooms: [...state.rooms, ensureRoomFloorTiles(action.payload)] }

    case 'SET_CURRENT_ROOM':
      return { ...state, currentRoom: ensureRoomFloorTiles(action.payload) }
    
    case 'DELETE_ROOM': {
      const remainingRooms = state.rooms.filter(room => room.id !== action.payload)
      const newCurrentRoom = state.currentRoom?.id === action.payload
        ? (remainingRooms[0] ? ensureRoomFloorTiles(remainingRooms[0]) : null)
        : (state.currentRoom ? ensureRoomFloorTiles(state.currentRoom) : null)
      return {
        ...state,
        rooms: remainingRooms,
        currentRoom: newCurrentRoom
      }
    }
    
    case 'RENAME_ROOM':
      return {
        ...state,
        rooms: state.rooms.map(room =>
          room.id === action.payload.roomId
            ? { ...room, name: action.payload.newName }
            : room
        ),
        currentRoom: state.currentRoom?.id === action.payload.roomId
          ? { ...state.currentRoom, name: action.payload.newName }
          : state.currentRoom
      }

    case 'UPDATE_ROOM_LAYOUT': {
      const { roomId, width, height } = action.payload
      const normalizedDoorway = normalizeDoorway(width, height, action.payload.doorway)

      const updateRoomLayout = (room: Room) => {
        if (room.id !== roomId) return room

        const filteredFurniture = room.furniture.filter(
          furniture =>
            furniture.x >= 0 &&
            furniture.y >= 0 &&
            furniture.x < width &&
            furniture.y < height
        )

        const existingFloorTiles = (room.floorTiles?.length ? room.floorTiles : createFullFloorTiles(room.width, room.height))
          .filter(tile => tile.x >= 0 && tile.x < width && tile.y >= 0 && tile.y < height)

        const tileSet = new Set(existingFloorTiles.map(tile => `${tile.x},${tile.y}`))

        if (width > room.width || height > room.height) {
          for (let x = 0; x < width; x++) {
            for (let y = 0; y < height; y++) {
              if ((x >= room.width || y >= room.height) && !tileSet.has(`${x},${y}`)) {
                existingFloorTiles.push({ x, y })
                tileSet.add(`${x},${y}`)
              }
            }
          }
        }

        const ensureFloorTile = (x: number, y: number) => {
          const key = `${x},${y}`
          if (!tileSet.has(key)) {
            existingFloorTiles.push({ x, y })
            tileSet.add(key)
          }
        }

        filteredFurniture.forEach(furniture => ensureFloorTile(furniture.x, furniture.y))

        const targetDoorway = normalizedDoorway ?? room.doorway
        const adjustedDoorway = adjustDoorwayForFloorTiles(targetDoorway, existingFloorTiles, width, height)

        const spawnPoint = normalizeSpawnPoint(
          width,
          height,
          action.payload.spawnPoint ?? defaultSpawnFromDoorway(width, height, adjustedDoorway)
        )

        if (spawnPoint) {
          ensureFloorTile(spawnPoint.x, spawnPoint.y)
        }

        return {
          ...room,
          width,
          height,
          floorTiles: existingFloorTiles,
          furniture: filteredFurniture,
          walls: buildRoomWalls(width, height, adjustedDoorway, existingFloorTiles),
          doorway: adjustedDoorway,
          spawnPoint
        }
      }

      const updatedRooms = state.rooms.map(updateRoomLayout)

      return {
        ...state,
        rooms: updatedRooms,
        currentRoom: state.currentRoom?.id === roomId
          ? updateRoomLayout(state.currentRoom)
          : state.currentRoom
      }
    }

    case 'TOGGLE_FLOOR_TILE': {
      if (!state.currentRoom) return state

      const { x, y } = action.payload
      if (x < 0 || x >= state.currentRoom.width || y < 0 || y >= state.currentRoom.height) {
        return state
      }

      const hasFurniture = state.currentRoom.furniture.some(f => f.x === x && f.y === y)
      const hasPlayer = state.players.some(player => Math.round(player.x) === x && Math.round(player.y) === y)
      const isSpawnTile = state.currentRoom.spawnPoint
        ? state.currentRoom.spawnPoint.x === x && state.currentRoom.spawnPoint.y === y
        : false

      if (hasFurniture || hasPlayer || isSpawnTile) {
        return state
      }

      const toggleFloor = (room: Room) => {
        if (room.id !== state.currentRoom!.id) return room

        const baseTiles = room.floorTiles && room.floorTiles.length > 0
          ? room.floorTiles
          : createFullFloorTiles(room.width, room.height)

        const hasTile = baseTiles.some(tile => tile.x === x && tile.y === y)
        const floorTiles = hasTile
          ? baseTiles.filter(tile => !(tile.x === x && tile.y === y))
          : [...baseTiles, { x, y }]

        const adjustedDoorway = adjustDoorwayForFloorTiles(room.doorway, floorTiles, room.width, room.height)

        return {
          ...room,
          floorTiles,
          doorway: adjustedDoorway,
          walls: buildRoomWalls(room.width, room.height, adjustedDoorway, floorTiles)
        }
      }

      const updatedRooms = state.rooms.map(toggleFloor)

      return {
        ...state,
        rooms: updatedRooms,
        currentRoom: toggleFloor(state.currentRoom)
      }
    }

    case 'FILL_ROOM_FLOOR': {
      if (!state.currentRoom) return state

      const fillRoom = (room: Room) => {
        if (room.id !== state.currentRoom!.id) return room

        const floorTiles = createFullFloorTiles(room.width, room.height)
        const adjustedDoorway = adjustDoorwayForFloorTiles(room.doorway, floorTiles, room.width, room.height)
        return {
          ...room,
          floorTiles,
          doorway: adjustedDoorway,
          walls: buildRoomWalls(room.width, room.height, adjustedDoorway, floorTiles)
        }
      }

      const updatedRooms = state.rooms.map(fillRoom)

      return {
        ...state,
        rooms: updatedRooms,
        currentRoom: fillRoom(state.currentRoom)
      }
    }

     case 'CLEAR_ROOM_FLOOR': {
       if (!state.currentRoom) return state

       const protectedTiles = new Set<string>()

       state.currentRoom.furniture.forEach(f => {
         protectedTiles.add(`${f.x},${f.y}`)
       })

       if (state.currentRoom.spawnPoint) {
         protectedTiles.add(`${state.currentRoom.spawnPoint.x},${state.currentRoom.spawnPoint.y}`)
       }

       state.players.forEach(player => {
         const px = Math.round(player.x)
         const py = Math.round(player.y)
         if (px >= 0 && px < state.currentRoom!.width && py >= 0 && py < state.currentRoom!.height) {
           protectedTiles.add(`${px},${py}`)
         }
       })

       const clearRoom = (room: Room) => {
         if (room.id !== state.currentRoom!.id) return room

         const baseTiles = room.floorTiles && room.floorTiles.length > 0
           ? room.floorTiles
           : createFullFloorTiles(room.width, room.height)

         const floorTiles = baseTiles.filter(tile => protectedTiles.has(`${tile.x},${tile.y}`))

         const adjustedDoorway = adjustDoorwayForFloorTiles(room.doorway, floorTiles, room.width, room.height)

         return {
           ...room,
           floorTiles,
           doorway: adjustedDoorway,
           walls: buildRoomWalls(room.width, room.height, adjustedDoorway, floorTiles)
         }
       }

       const updatedRooms = state.rooms.map(clearRoom)

       return {
         ...state,
         rooms: updatedRooms,
         currentRoom: clearRoom(state.currentRoom)
       }
     }

     case 'SET_FLOOR_TEXTURE': {
       const { roomId, texture } = action.payload
       
       const updateRoomTexture = (room: Room) => {
         if (room.id !== roomId) return room
         return { ...room, floorTexture: texture }
       }

       return {
         ...state,
         rooms: state.rooms.map(updateRoomTexture),
         currentRoom: state.currentRoom?.id === roomId
           ? updateRoomTexture(state.currentRoom)
           : state.currentRoom
       }
     }

     case 'SET_TILE_TEXTURE': {
       const { roomId, x, y, texture } = action.payload
       
       const updateTileTexture = (room: Room) => {
         if (room.id !== roomId) return room
         
         const updatedFloorTiles = room.floorTiles.map(tile => 
           tile.x === x && tile.y === y 
             ? { ...tile, texture }
             : tile
         )
         
         return { ...room, floorTiles: updatedFloorTiles }
       }

       return {
         ...state,
         rooms: state.rooms.map(updateTileTexture),
         currentRoom: state.currentRoom?.id === roomId
           ? updateTileTexture(state.currentRoom)
           : state.currentRoom
       }
     }

    case 'SET_STYLE_MODE':
      return { ...state, styleMode: action.payload }

    case 'TOGGLE_WINDOW': {
      if (!state.currentRoom) return state

      // Every wall edge on the clicked tile flips together. Almost every tile
      // has exactly one, and picking between two by cursor position at this
      // scale would be a coin toss.
      const edges = state.currentRoom.walls.filter(
        wall => wall.x === action.payload.x && wall.y === action.payload.y
      )
      if (edges.length === 0) return state

      const existing = state.currentRoom.windows ?? []
      const isOpen = edges.every(edge =>
        existing.some(w => w.x === edge.x && w.y === edge.y && w.edge === edge.edge)
      )

      const windows = isOpen
        ? existing.filter(
            w => !edges.some(edge => w.x === edge.x && w.y === edge.y && w.edge === edge.edge)
          )
        : [
            ...existing.filter(
              w => !edges.some(edge => w.x === edge.x && w.y === edge.y && w.edge === edge.edge)
            ),
            ...edges.map(edge => ({ x: edge.x, y: edge.y, edge: edge.edge }))
          ]

      const applyWindows = (room: Room) =>
        room.id === state.currentRoom!.id ? { ...room, windows } : room

      return {
        ...state,
        rooms: state.rooms.map(applyWindows),
        currentRoom: { ...state.currentRoom, windows }
      }
    }

    case 'SET_PLACEMENT_DIRECTION':
      return { ...state, placementDirection: action.payload }

    case 'ADD_FURNITURE': {
      if (!state.currentRoom) return state

      // Both copies, or the room in `rooms` stays empty: leaving the current
      // room and coming back already lost the furniture, and saving would have
      // persisted the empty one.
      const furniture = [...state.currentRoom.furniture, action.payload]
      const roomId = state.currentRoom.id

      return {
        ...state,
        rooms: state.rooms.map(room => (room.id === roomId ? { ...room, furniture } : room)),
        currentRoom: { ...state.currentRoom, furniture }
      }
    }
    
    case 'ADD_PLAYER':
      return {
        ...state,
        players: [...state.players, action.payload]
      }
    
    case 'SET_CURRENT_PLAYER':
      return { ...state, currentPlayerId: action.payload }
    
    case 'MOVE_PLAYER':
      return {
        ...state,
        players: state.players.map(player =>
          player.id === action.payload.playerId
            ? { 
                ...player, 
                targetX: action.payload.x,
                targetY: action.payload.y,
                isMoving: true,
                path: action.payload.path || [],
                pathIndex: 0,
                // Setting off ends whatever you were doing. Left set, the old
                // action keeps resolving to the spot behind it, so someone
                // walking away from a chair drags its seat offset and its
                // facing along for the first few steps.
                action: 'idle',
                actionTimer: 0,
                actionDuration: 0,
                // A new destination replaces any previous intent, so a walk
                // ordered mid-errand cancels the errand.
                intent: action.payload.intent ?? null
              }
            : player
        )
      }
    
    case 'SET_PLAYER_ACTION':
      return {
        ...state,
        players: state.players.map(player =>
          player.id === action.payload.playerId
            ? {
                ...player,
                action: action.payload.action,
                actionTimer: 0,
                actionDuration: action.payload.durationMs ?? 0
              }
            : player
        )
      }
    
    case 'SET_PLAYER_APPEARANCE':
      return {
        ...state,
        players: state.players.map(player =>
          player.id === action.payload.playerId
            ? { ...player, appearance: action.payload.appearance }
            : player
        )
      }

    case 'ADD_CHAT_MESSAGE':
      return {
        ...state,
        chatMessages: [...state.chatMessages.slice(-49), action.payload]
      }
    
    case 'SET_SHOW_CHAT':
      return { ...state, showChat: action.payload }
    
    case 'SHOW_CONTEXT_MENU':
      return {
        ...state,
        contextMenuVisible: true,
        contextMenuTarget: action.payload.player,
        currentPlayerId: action.payload.player.id
      }
    
    case 'HIDE_CONTEXT_MENU':
      return {
        ...state,
        contextMenuVisible: false,
        contextMenuTarget: null
      }
    
    case 'SET_HOVER_GRID':
      return { ...state, hoverGridPos: action.payload }
    
    case 'SET_PREVIEW_FURNITURE':
      return { ...state, previewFurniture: action.payload }
    
    default:
      return state
  }
}

// Context
const GameContext = createContext<{
  state: GameState
  dispatch: React.Dispatch<GameAction>
  roomManager: {
    createRoom: (name: string, width: number, height: number, floorTexture?: string) => Room
    selectRoom: (room: Room) => void
    deleteRoom: (roomId: string) => void
    renameRoom: (roomId: string, newName: string) => void
    updateLayout: (roomId: string, layout: RoomLayoutUpdate) => void
    setFloorTexture: (roomId: string, texture: string) => void
    setTileTexture: (roomId: string, x: number, y: number, texture: string) => void
    /** Discard the saved world and reload from the shipped layouts. */
    resetWorld: () => void
  }
  /** Change how the local player looks, and remember it. */
  setAppearance: (appearance: Appearance) => void
} | null>(null)

// Helper function to generate unique IDs
const generateId = (prefix: string = '') => `${prefix}${Date.now()}-${Math.random().toString(36).substr(2, 9)}`

const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max)

const createFullFloorTiles = (width: number, height: number, texture?: string) => {
  const tiles: Array<{ x: number; y: number; texture?: string }> = []

  for (let x = 0; x < width; x++) {
    for (let y = 0; y < height; y++) {
      tiles.push({ x, y, texture })
    }
  }

  return tiles
}

const adjustDoorwayForFloorTiles = (
  doorway: { x: number; y: number; type: 'north-east' | 'north-west' } | undefined,
  floorTiles: Array<{ x: number; y: number }> | undefined,
  width: number,
  height: number
) => {
  if (!doorway) return undefined

  const effectiveFloorTiles = floorTiles && floorTiles.length > 0
    ? floorTiles
    : createFullFloorTiles(width, height)

  if (doorway.type === 'north-east') {
    const columnTiles = effectiveFloorTiles.filter(tile => tile.x === doorway.x)
    if (columnTiles.length === 0) return undefined
    const minY = Math.min(...columnTiles.map(tile => tile.y))
    return { x: doorway.x, y: minY - 1, type: 'north-east' as const }
  }

  const rowTiles = effectiveFloorTiles.filter(tile => tile.y === doorway.y)
  if (rowTiles.length === 0) return undefined
  const minX = Math.min(...rowTiles.map(tile => tile.x))
  return { x: minX - 1, y: doorway.y, type: 'north-west' as const }
}

const ensureRoomFloorTiles = (room: Room): Room => {
  const floorTiles = room.floorTiles && room.floorTiles.length > 0
    ? room.floorTiles
    : createFullFloorTiles(room.width, room.height)

  const doorway = adjustDoorwayForFloorTiles(room.doorway, floorTiles, room.width, room.height)

  return {
    ...room,
    floorTiles,
    doorway,
    walls: buildRoomWalls(room.width, room.height, doorway, floorTiles)
  }
}

const normalizeDoorway = (
  width: number,
  height: number,
  doorway?: { x: number; y: number; type: 'north-east' | 'north-west' }
) => {
  if (!doorway) return undefined

  if (doorway.type === 'north-east') {
    const x = clamp(Math.round(doorway.x), 0, Math.max(width - 1, 0))
    return { x, y: -1, type: 'north-east' as const }
  }

  const y = clamp(Math.round(doorway.y), 0, Math.max(height - 1, 0))
  return { x: -1, y, type: 'north-west' as const }
}

const normalizeSpawnPoint = (width: number, height: number, spawnPoint?: { x: number; y: number }) => {
  if (!spawnPoint) return undefined

  const x = clamp(Math.round(spawnPoint.x), 0, Math.max(width - 1, 0))
  const y = clamp(Math.round(spawnPoint.y), 0, Math.max(height - 1, 0))

  return { x, y }
}

export function buildRoomWalls(
  width: number,
  height: number,
  doorway?: { x: number; y: number; type: 'north-east' | 'north-west' },
  floorTiles?: Array<{ x: number; y: number }>
) {
  const effectiveFloorTiles = floorTiles && floorTiles.length > 0
    ? floorTiles
    : createFullFloorTiles(width, height)

  const tileSet = new Set(effectiveFloorTiles.map(tile => `${tile.x},${tile.y}`))
  const walls: Array<{ x: number; y: number; edge: WallEdge }> = []

  effectiveFloorTiles.forEach(tile => {
    // A tile with no floor to its -y gets a panel on that edge, and so on. The
    // doorway is simply a segment we skip.
    const westKey = `${tile.x},${tile.y - 1}`
    if (!tileSet.has(westKey)) {
      if (!(doorway?.type === 'north-east' && doorway.x === tile.x && doorway.y === tile.y - 1)) {
        walls.push({ x: tile.x, y: tile.y, edge: 'west' })
      }
    }

    const northKey = `${tile.x - 1},${tile.y}`
    if (!tileSet.has(northKey)) {
      if (!(doorway?.type === 'north-west' && doorway.x === tile.x - 1 && doorway.y === tile.y)) {
        walls.push({ x: tile.x, y: tile.y, edge: 'north' })
      }
    }
  })

  return walls
}

const defaultSpawnFromDoorway = (
  width: number,
  height: number,
  doorway?: { x: number; y: number; type: 'north-east' | 'north-west' }
) => {
  if (!doorway) {
    return { x: Math.floor(width / 2), y: Math.floor(height / 2) }
  }

  if (doorway.type === 'north-east') {
    return { x: clamp(doorway.x, 0, Math.max(width - 1, 0)), y: 0 }
  }

  return { x: 0, y: clamp(doorway.y, 0, Math.max(height - 1, 0)) }
}

const sanitizeLayoutRow = (row: string) => row.replace(/\s+$/u, '')

const determineDoorwayFromLayout = (
  doorCandidate: { x: number; y: number; orientation: 'north-east' | 'north-west' } | undefined,
  width: number,
  height: number
) => {
  if (!doorCandidate) return undefined

  if (doorCandidate.orientation === 'north-east') {
    return normalizeDoorway(width, height, { x: doorCandidate.x, y: -1, type: 'north-east' })
  }

  return normalizeDoorway(width, height, { x: -1, y: doorCandidate.y, type: 'north-west' })
}

const layoutCharIsFloor = (char: string) => {
  const normalized = char.toLowerCase()
  return normalized === 'o' || normalized === 'd' || normalized === 's'
}

export const createRoomFromLayoutDefinition = (definition: RoomLayoutDefinition): Room => {
  const rows = definition.layout.map(sanitizeLayoutRow)
  const height = rows.length || 1
  const width = rows.reduce((max, row) => Math.max(max, row.length), 0) || 1

  const floorTiles: Array<{ x: number; y: number }> = []
  let doorCandidate: { x: number; y: number; orientation: 'north-east' | 'north-west' } | undefined
  let spawnCandidate: { x: number; y: number } | undefined

  rows.forEach((row, y) => {
    for (let x = 0; x < width; x++) {
      const char = row[x] ?? 'x'
      if (layoutCharIsFloor(char)) {
        floorTiles.push({ x, y })
      }

      if ((char === 'd' || char === 'D') && !doorCandidate) {
        const orientation: 'north-east' | 'north-west' = x === 0 ? 'north-west' : 'north-east'
        doorCandidate = { x, y, orientation }
      }

      if ((char === 's' || char === 'S') && !spawnCandidate) {
        spawnCandidate = { x, y }
      }
    }
  })

  const uniqueFloorTiles = Array.from(
    new Map(floorTiles.map(tile => [`${tile.x},${tile.y}`, tile])).values()
  )

  const doorway = determineDoorwayFromLayout(doorCandidate, width, height)
  const baseFloorTiles = uniqueFloorTiles.length > 0
    ? uniqueFloorTiles
    : createFullFloorTiles(width, height)
  const adjustedDoorway = adjustDoorwayForFloorTiles(doorway, baseFloorTiles, width, height)

  const spawnPoint = normalizeSpawnPoint(
    width,
    height,
    spawnCandidate ?? defaultSpawnFromDoorway(width, height, adjustedDoorway)
  )

  const baseRoom: Room = {
    id: definition.id ?? generateId('room-'),
    name: definition.name,
    width,
    height,
    floorTiles: baseFloorTiles,
    furniture: [],
    walls: [],
    doorway: adjustedDoorway,
    spawnPoint
  }

  return ensureRoomFloorTiles(baseRoom)
}

export const serializeRoomLayout = (room: Room): RoomLayoutDefinition => {
  const grid = Array.from({ length: room.height }, () => Array.from({ length: room.width }, () => 'x'))
  const floorTiles = room.floorTiles && room.floorTiles.length > 0
    ? room.floorTiles
    : createFullFloorTiles(room.width, room.height)

  floorTiles.forEach(tile => {
    if (tile.y >= 0 && tile.y < room.height && tile.x >= 0 && tile.x < room.width) {
      grid[tile.y][tile.x] = 'o'
    }
  })

  if (room.spawnPoint) {
    const { x, y } = room.spawnPoint
    if (y >= 0 && y < room.height && x >= 0 && x < room.width) {
      grid[y][x] = 's'
    }
  }

  if (room.doorway) {
    if (room.doorway.type === 'north-east') {
      const columnTiles = floorTiles.filter(tile => tile.x === room.doorway!.x)
      if (columnTiles.length > 0) {
        const minY = Math.min(...columnTiles.map(tile => tile.y))
        if (minY >= 0 && minY < room.height && room.doorway!.x >= 0 && room.doorway!.x < room.width) {
          grid[minY][room.doorway!.x] = 'd'
        }
      }
    } else {
      const rowTiles = floorTiles.filter(tile => tile.y === room.doorway!.y)
      if (rowTiles.length > 0) {
        const minX = Math.min(...rowTiles.map(tile => tile.x))
        if (room.doorway!.y >= 0 && room.doorway!.y < room.height && minX >= 0 && minX < room.width) {
          grid[room.doorway!.y][minX] = 'd'
        }
      }
    }
  }

  const layout = grid.map(row => row.join(''))

  return {
    id: room.id,
    name: room.name,
    layout
  }
}

// Helper function to create a new room
const createRoom = (name: string, width: number, height: number, floorTexture?: string): Room => {
  const doorway = normalizeDoorway(width, height, {
    x: Math.floor(width / 2),
    y: -1,
    type: 'north-east'
  })

  const spawnPoint = normalizeSpawnPoint(width, height, {
    x: doorway?.x ?? Math.floor(width / 2),
    y: 0
  })

  const adjustedDoorway = adjustDoorwayForFloorTiles(doorway, undefined, width, height)

  return {
    id: generateId('room-'),
    name,
    width,
    height,
    floorTiles: createFullFloorTiles(width, height, floorTexture),
    furniture: [],
    walls: buildRoomWalls(width, height, adjustedDoorway),
    doorway: adjustedDoorway,
    spawnPoint,
    floorTexture
  }
}

// Provider
export function GameProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(gameReducer, initialState)

  /** The last document we stored, so revisions increment rather than reset. */
  const savedWorld = useRef<WorldDocument | null>(null)
  /** Saving stays off until the world is loaded, or boot would overwrite it. */
  const hydrated = useRef(false)

  // Dev-only inspection hook. Reading the live room and player state from the
  // console (or a browser test) beats inferring it from canvas pixels.
  useEffect(() => {
    if (import.meta.env.DEV) {
      const debugWindow = window as unknown as { __isogame?: GameState }
      debugWindow.__isogame = state
    }
  }, [state])

  // Initialize game with default room and players
  useEffect(() => {
    const layoutDefinitions = Array.isArray(roomLayoutDefinitions)
      ? (roomLayoutDefinitions as RoomLayoutDefinition[])
      : []

    const validLayoutDefinitions = layoutDefinitions.filter(
      (definition): definition is RoomLayoutDefinition =>
        !!definition &&
        typeof definition.name === 'string' &&
        Array.isArray(definition.layout)
    )

    const predefinedRooms = validLayoutDefinitions.map(createRoomFromLayoutDefinition)
    const fallbackRooms = predefinedRooms.length > 0
      ? predefinedRooms
      : [createRoom('Main Room', 20, 15)]

    // A saved world wins over the shipped layouts; the layouts are the seed for
    // a first visit, not the source of truth afterwards.
    let cancelled = false

    const bootstrap = async () => {
      const [saved, profile] = await Promise.all([
        getWorldStore().load(),
        getProfileStore().load()
      ])
      if (cancelled) return

      const restored = saved?.rooms?.length
        ? saved.rooms.map(fromPersistedRoom)
        : null

      if (restored) savedWorld.current = saved

      const roomsToLoad = restored ?? fallbackRooms
      roomsToLoad.forEach(room => {
        dispatch({ type: 'ADD_ROOM', payload: room })
      })

      const defaultRoom =
        roomsToLoad.find(room => room.id === saved?.currentRoomId) ?? roomsToLoad[0]
      if (!defaultRoom) return

      dispatch({ type: 'SET_CURRENT_ROOM', payload: defaultRoom })
      startPlayers(defaultRoom, profile?.appearance ?? DEFAULT_APPEARANCE)
      hydrated.current = true
    }

    void bootstrap()
    return () => {
      cancelled = true
    }
  }, [])

  /**
   * Persist the world whenever the authored parts of it change.
   *
   * Debounced because painting a floor fires a dispatch per tile, and a save
   * per tile would be pointless locally and abusive against a server.
   */
  useEffect(() => {
    if (!hydrated.current || state.rooms.length === 0) return

    const timer = window.setTimeout(() => {
      const document = toWorldDocument(
        state.rooms,
        state.currentRoom?.id ?? null,
        savedWorld.current
      )
      void getWorldStore()
        .save(document)
        .then(stored => {
          savedWorld.current = stored
        })
    }, 600)

    return () => window.clearTimeout(timer)
  }, [state.rooms, state.currentRoom])

  /**
   * Seed the guests at the room's spawn point.
   *
   * Only the first is ours; the rest are given deterministic looks derived from
   * their id, so a room reads as populated by different people without any of
   * it being authored or stored.
   */
  const startPlayers = (defaultRoom: Room, appearance: Appearance) => {
    const spawnX = defaultRoom.spawnPoint?.x || 5
    const spawnY = defaultRoom.spawnPoint?.y || 5
    const outfits = getOutfits().map(outfit => outfit.id)
    const hairStyles = getHairStyles().map(style => style.id)

    const guests = [
      { name: 'Player1', color: '#FF6B6B' },
      { name: 'Player2', color: '#4ECDC4' },
      { name: 'Player3', color: '#45B7D1' },
      { name: 'Player4', color: '#96CEB4' }
    ]

    guests.forEach((guest, id) => {
      // Staggered so no two guests share a screen column. The old +1,+1 per
      // guest is a straight line *down the screen* in isometric, which stacked
      // all four into one overlapping pile.
      const x = spawnX + id
      const y = spawnY + (id % 2) * 2

      dispatch({
        type: 'ADD_PLAYER',
        payload: {
          id,
          ...guest,
          x,
          y,
          targetX: x,
          targetY: y,
          size: 0.8,
          isMoving: false,
          moveSpeed: 0.1,
          moveTimer: 0,
          moveDelay: 400,
          path: [],
          pathIndex: 0,
          action: 'idle',
          actionTimer: 0,
          actionDuration: 0,
          intent: null,
          lastDirection: 'south',
          appearance: id === 0 ? appearance : appearanceForSeed(id, outfits, hairStyles)
        }
      })
    })
  }

  // Room management functions
    const roomManager = {
      /** Forget the saved world and reload from the shipped layouts. */
      resetWorld: async () => {
        hydrated.current = false
        savedWorld.current = null
        await getWorldStore().clear()
        window.location.reload()
      },
      createRoom: (name: string, width: number, height: number, floorTexture?: string) => {
        const newRoom = createRoom(name, width, height, floorTexture)
        dispatch({ type: 'ADD_ROOM', payload: newRoom })
        return newRoom
      },
      selectRoom: (room: Room) => {
        dispatch({ type: 'SET_CURRENT_ROOM', payload: room })
      },
      deleteRoom: (roomId: string) => {
        dispatch({ type: 'DELETE_ROOM', payload: roomId })
      },
      renameRoom: (roomId: string, newName: string) => {
        dispatch({ type: 'RENAME_ROOM', payload: { roomId, newName } })
      },
      updateLayout: (roomId: string, layout: RoomLayoutUpdate) => {
        dispatch({ type: 'UPDATE_ROOM_LAYOUT', payload: { roomId, ...layout } })
      },
      setFloorTexture: (roomId: string, texture: string) => {
        dispatch({ type: 'SET_FLOOR_TEXTURE', payload: { roomId, texture } })
      },
      setTileTexture: (roomId: string, x: number, y: number, texture: string) => {
        dispatch({ type: 'SET_TILE_TEXTURE', payload: { roomId, x, y, texture } })
      }
    }

  /**
   * Dress the local player.
   *
   * Saved immediately rather than debounced: unlike painting a floor, this is
   * one deliberate change per interaction, and losing the last one to a reload
   * is exactly the thing people notice.
   */
  const setAppearance = (appearance: Appearance) => {
    dispatch({
      type: 'SET_PLAYER_APPEARANCE',
      payload: { playerId: state.currentPlayerId, appearance }
    })
    void getProfileStore().save(toProfileDocument(appearance))
  }

  return (
    <GameContext.Provider value={{ state, dispatch, roomManager, setAppearance }}>
      {children}
    </GameContext.Provider>
  )
}

// Hook
// This hook intentionally lives alongside the provider for convenient imports.
// eslint-disable-next-line react-refresh/only-export-components
export function useGame() {
  const context = useContext(GameContext)
  if (!context) {
    throw new Error('useGame must be used within a GameProvider')
  }
  return context
}
