/**
 * The furniture catalogue.
 *
 * These definitions are no longer hand-maintained. They are generated by the
 * Sprite Factory (tools/sprite-factory) alongside the sprites themselves, so an
 * item's footprint, collision box, interaction spots and artwork can never drift
 * apart - they come out of the same 3D model in one pass.
 *
 * To change a piece of furniture, edit tools/sprite-factory/src/catalog.ts and
 * run `npm run sprites`.
 */

import { Furniture, FurnitureDefinition, FurnitureDirection, FurniturePosition } from '../context/GameContext'
import generated from './furnitureDefinitions.generated.json'

export const FURNITURE_DEFINITIONS = generated as unknown as Record<string, FurnitureDefinition>

export const getFurnitureDefinition = (id: string): FurnitureDefinition | null => {
  return FURNITURE_DEFINITIONS[id] || null
}

export const getFurnitureByCategory = (category: FurnitureDefinition['category']): FurnitureDefinition[] => {
  return Object.values(FURNITURE_DEFINITIONS).filter(furniture => furniture.category === category)
}

export const getAllFurnitureDefinitions = (): FurnitureDefinition[] => {
  return Object.values(FURNITURE_DEFINITIONS)
}

/** Furniture that can only be placed on a wall or hung from the ceiling. */
export const getMountedFurniture = (): FurnitureDefinition[] => {
  return getAllFurnitureDefinitions().filter(furniture => furniture.placement && furniture.placement !== 'floor')
}

/** The order rotation steps through, matching the pipeline's quarter turns. */
const DIRECTION_CYCLE: FurnitureDirection[] = ['south', 'west', 'north', 'east']

/** Orientations this piece was actually rendered in. Wall items only have two. */
export const getAvailableDirections = (definition: FurnitureDefinition): FurnitureDirection[] => {
  if (!definition.sprites) return []
  return DIRECTION_CYCLE.filter(direction => definition.sprites?.[direction])
}

/**
 * Next orientation when the player rotates a piece.
 *
 * Steps through the orientations that exist rather than blindly adding 90
 * degrees, so rotating a wall lamp flips between its two frames instead of
 * landing on one that was never rendered.
 */
export const getNextDirection = (
  definition: FurnitureDefinition,
  current?: FurnitureDirection
): FurnitureDirection | undefined => {
  const available = getAvailableDirections(definition)
  if (available.length === 0) return undefined

  const start = current ?? definition.defaultDirection ?? available[0]
  const index = available.indexOf(start)
  return available[(index + 1) % available.length]
}

export interface ResolvedInteraction {
  furniture: Furniture
  spot: FurniturePosition
  type: string
  /** Milliseconds the action lasts. 0 means until the player walks away. */
  duration: number
}

/**
 * The interactions of a piece in the orientation it is actually placed in.
 *
 * The per-direction sprite carries spots that were rotated with the model, so
 * they win over the definition's defaults; falling back to the definition keeps
 * older generated data working.
 */
const interactionsOf = (piece: Furniture) => {
  const sprite = piece.definition.sprites?.[piece.direction ?? piece.definition.defaultDirection ?? '']
  return sprite?.interactions ?? piece.definition.interactions ?? []
}

/** Tiles a piece occupies in the orientation it is placed in. */
export const getFootprint = (piece: Furniture): { width: number; height: number } => {
  const sprite = piece.definition.sprites?.[piece.direction ?? piece.definition.defaultDirection ?? '']
  return sprite?.footprint ?? { width: piece.definition.width, height: piece.definition.height }
}

export const occupiesTile = (piece: Furniture, x: number, y: number): boolean => {
  const footprint = getFootprint(piece)
  return (
    x >= piece.x && x < piece.x + footprint.width && y >= piece.y && y < piece.y + footprint.height
  )
}

/** The piece drawn on a tile, topmost first. */
export const findFurnitureAt = (furniture: Furniture[], x: number, y: number): Furniture | null => {
  // Later pieces are drawn over earlier ones, so a click hits the last match.
  for (let index = furniture.length - 1; index >= 0; index--) {
    if (occupiesTile(furniture[index], x, y)) return furniture[index]
  }
  return null
}

/**
 * Find the interaction spot a player is standing on, if any.
 *
 * Resolved at draw time rather than stored on the player, so it stays correct
 * when furniture is moved or removed out from under them.
 */
export const findInteractionSpot = (
  furniture: Furniture[],
  tileX: number,
  tileY: number,
  types: string[]
): ResolvedInteraction | null => {
  for (const piece of furniture) {
    for (const interaction of interactionsOf(piece)) {
      if (!types.includes(interaction.type)) continue

      for (const spot of interaction.positions) {
        if (piece.x + spot.x === tileX && piece.y + spot.y === tileY) {
          return { furniture: piece, spot, type: interaction.type, duration: interaction.duration ?? 0 }
        }
      }
    }
  }

  return null
}

/** Every spot of the given types on one piece, in world tile coordinates. */
export const listInteractionSpots = (
  piece: Furniture,
  types: string[]
): Array<ResolvedInteraction & { tileX: number; tileY: number }> => {
  const found: Array<ResolvedInteraction & { tileX: number; tileY: number }> = []

  for (const interaction of interactionsOf(piece)) {
    if (!types.includes(interaction.type)) continue
    for (const spot of interaction.positions) {
      found.push({
        furniture: piece,
        spot,
        type: interaction.type,
        duration: interaction.duration ?? 0,
        tileX: piece.x + spot.x,
        tileY: piece.y + spot.y
      })
    }
  }

  return found
}
