/**
 * The furniture catalogue.
 *
 * These definitions are no longer hand-maintained. They are generated by the
 * Sprite Factory (tools/sprite-factory) alongside the sprites themselves, so an
 * item's footprint, collision box, interaction spots and artwork can never drift
 * apart - they come out of the same 3D model in one pass.
 *
 * To change a piece of furniture, edit tools/sprite-factory/src/catalog.ts and
 * run `npm run sprites`.
 */

import { Furniture, FurnitureDefinition, FurnitureDirection, FurniturePosition } from '../context/GameContext'
import generated from './furnitureDefinitions.generated.json'

export const FURNITURE_DEFINITIONS = generated as unknown as Record<string, FurnitureDefinition>

export const getFurnitureDefinition = (id: string): FurnitureDefinition | null => {
  return FURNITURE_DEFINITIONS[id] || null
}

export const getFurnitureByCategory = (category: FurnitureDefinition['category']): FurnitureDefinition[] => {
  return Object.values(FURNITURE_DEFINITIONS).filter(furniture => furniture.category === category)
}

export const getAllFurnitureDefinitions = (): FurnitureDefinition[] => {
  return Object.values(FURNITURE_DEFINITIONS)
}

/** Furniture that can only be placed on a wall or hung from the ceiling. */
export const getMountedFurniture = (): FurnitureDefinition[] => {
  return getAllFurnitureDefinitions().filter(furniture => furniture.placement && furniture.placement !== 'floor')
}

/** The order rotation steps through, matching the pipeline's quarter turns. */
const DIRECTION_CYCLE: FurnitureDirection[] = ['south', 'west', 'north', 'east']

/** Orientations this piece was actually rendered in. Wall items only have two. */
export const getAvailableDirections = (definition: FurnitureDefinition): FurnitureDirection[] => {
  if (!definition.sprites) return []
  return DIRECTION_CYCLE.filter(direction => definition.sprites?.[direction])
}

/**
 * Next orientation when the player rotates a piece.
 *
 * Steps through the orientations that exist rather than blindly adding 90
 * degrees, so rotating a wall lamp flips between its two frames instead of
 * landing on one that was never rendered.
 */
export const getNextDirection = (
  definition: FurnitureDefinition,
  current?: FurnitureDirection
): FurnitureDirection | undefined => {
  const available = getAvailableDirections(definition)
  if (available.length === 0) return undefined

  const start = current ?? definition.defaultDirection ?? available[0]
  const index = available.indexOf(start)
  return available[(index + 1) % available.length]
}

export interface ResolvedInteraction {
  furniture: Furniture
  spot: FurniturePosition
  type: string
  /** Milliseconds the action lasts. 0 means until the player walks away. */
  duration: number
}

/**
 * The interactions of a piece in the orientation it is actually placed in.
 *
 * The per-direction sprite carries spots that were rotated with the model, so
 * they win over the definition's defaults; falling back to the definition keeps
 * older generated data working.
 */
const interactionsOf = (piece: Furniture) => {
  const sprite = piece.definition.sprites?.[piece.direction ?? piece.definition.defaultDirection ?? '']
  return sprite?.interactions ?? piece.definition.interactions ?? []
}

/** Tiles a definition occupies in a given orientation. */
export const getDefinitionFootprint = (
  definition: FurnitureDefinition,
  direction?: string
): { width: number; height: number } => {
  const sprite = definition.sprites?.[direction ?? definition.defaultDirection ?? '']
  return sprite?.footprint ?? { width: definition.width, height: definition.height }
}

/** Tiles a piece occupies in the orientation it is placed in. */
export const getFootprint = (piece: Furniture): { width: number; height: number } => {
  return getDefinitionFootprint(piece.definition, piece.direction)
}

/**
 * Which plane a piece lives on.
 *
 * Placement used to be a plain rectangle overlap, so a ceiling lamp reserved the
 * whole tile beneath it and a rug could not go under anything at all. These are
 * four physically separate planes, and only pieces sharing one can be in each
 * other's way.
 */
export type PlacementLayer = 'floor' | 'decal' | 'wall' | 'ceiling'

export const placementLayer = (definition: FurnitureDefinition): PlacementLayer => {
  const placement = definition.placement ?? 'floor'
  if (placement !== 'floor') return placement
  // Flat and walked over: a rug lies on the floor surface, under the furniture.
  return definition.walkable && definition.collision.height === 0 ? 'decal' : 'floor'
}

export interface PlacementPlan {
  valid: boolean
  /**
   * Screen pixels to raise the piece by, from whatever it is resting on.
   * Zero for anything on the floor.
   */
  z: number
  /** The piece it rests on, when stacked. */
  support: Furniture | null
}

const INVALID: PlacementPlan = { valid: false, z: 0, support: null }

interface PlacementQuery {
  definition: FurnitureDefinition
  direction?: string
  x: number
  y: number
  roomWidth: number
  roomHeight: number
  floorTiles: Array<{ x: number; y: number }>
  furniture: Furniture[]
  players: Array<{ x: number; y: number }>
}

/**
 * Can this piece go here, and how high does it sit?
 *
 * Two things share one walk over the existing furniture, because they are the
 * same question: whatever is already on these tiles either blocks the placement
 * or is the thing being stacked on.
 */
export const planPlacement = (query: PlacementQuery): PlacementPlan => {
  const { definition, x, y } = query
  const layer = placementLayer(definition)
  const { width, height } = getDefinitionFootprint(definition, query.direction)

  for (let dx = 0; dx < width; dx++) {
    for (let dy = 0; dy < height; dy++) {
      const tileX = x + dx
      const tileY = y + dy
      if (tileX < 0 || tileX >= query.roomWidth || tileY < 0 || tileY >= query.roomHeight) {
        return INVALID
      }
      if (!query.floorTiles.some(tile => tile.x === tileX && tile.y === tileY)) return INVALID
    }
  }

  const overlaps = (piece: Furniture) => {
    const footprint = getFootprint(piece)
    return !(
      x + width <= piece.x ||
      piece.x + footprint.width <= x ||
      y + height <= piece.y ||
      piece.y + footprint.height <= y
    )
  }

  // Whether a piece covers every tile this one needs - you cannot rest a table
  // half on a crate.
  const contains = (piece: Furniture) => {
    const footprint = getFootprint(piece)
    return (
      x >= piece.x &&
      y >= piece.y &&
      x + width <= piece.x + footprint.width &&
      y + height <= piece.y + footprint.height
    )
  }

  let support: Furniture | null = null

  for (const piece of query.furniture) {
    if (placementLayer(piece.definition) !== layer) continue
    if (!overlaps(piece)) continue

    // On any plane but the floor, sharing space is simply a clash. On the floor
    // there is one way to share it: by standing on top.
    if (layer !== 'floor') return INVALID
    if (!piece.definition.stackable || !piece.definition.surface) return INVALID
    if (!contains(piece)) return INVALID

    // A stack of surfaces resolves to the highest one.
    if (!support || piece.z > support.z) support = piece
  }

  // Only something that will actually be in a player's way cares where they
  // are - and nothing standing on a table can be, since they cannot get there.
  if (!support && definition.collision.blocksMovement) {
    for (const player of query.players) {
      const px = Math.round(player.x)
      const py = Math.round(player.y)
      if (px >= x && px < x + width && py >= y && py < y + height) return INVALID
    }
  }

  return {
    valid: true,
    z: support ? support.z + (support.definition.surface?.offsetY ?? 0) : 0,
    support
  }
}

export const occupiesTile = (piece: Furniture, x: number, y: number): boolean => {
  const footprint = getFootprint(piece)
  return (
    x >= piece.x && x < piece.x + footprint.width && y >= piece.y && y < piece.y + footprint.height
  )
}

/** The piece drawn on a tile, topmost first. */
export const findFurnitureAt = (furniture: Furniture[], x: number, y: number): Furniture | null => {
  // Later pieces are drawn over earlier ones, so a click hits the last match.
  for (let index = furniture.length - 1; index >= 0; index--) {
    if (occupiesTile(furniture[index], x, y)) return furniture[index]
  }
  return null
}

/**
 * Find the interaction spot a player is standing on, if any.
 *
 * Resolved at draw time rather than stored on the player, so it stays correct
 * when furniture is moved or removed out from under them.
 */
export const findInteractionSpot = (
  furniture: Furniture[],
  tileX: number,
  tileY: number,
  types: string[]
): ResolvedInteraction | null => {
  for (const piece of furniture) {
    for (const interaction of interactionsOf(piece)) {
      if (!types.includes(interaction.type)) continue

      for (const spot of interaction.positions) {
        if (piece.x + spot.x === tileX && piece.y + spot.y === tileY) {
          return { furniture: piece, spot, type: interaction.type, duration: interaction.duration ?? 0 }
        }
      }
    }
  }

  return null
}

/** Every spot of the given types on one piece, in world tile coordinates. */
export const listInteractionSpots = (
  piece: Furniture,
  types: string[]
): Array<ResolvedInteraction & { tileX: number; tileY: number }> => {
  const found: Array<ResolvedInteraction & { tileX: number; tileY: number }> = []

  for (const interaction of interactionsOf(piece)) {
    if (!types.includes(interaction.type)) continue
    for (const spot of interaction.positions) {
      found.push({
        furniture: piece,
        spot,
        type: interaction.type,
        duration: interaction.duration ?? 0,
        tileX: piece.x + spot.x,
        tileY: piece.y + spot.y
      })
    }
  }

  return found
}
